version: '3.9'
services:
  # api
  api:
    build:
      context: .
      dockerfile: ./docker/local/flask/Dockerfile
    container_name: bookstore-api
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - .:/app
    networks:
      - flask_network
    depends_on:
      - postgres_db

  # postgres
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - flask_network
    ports:
      - '5432:5432'

  # nginx
  nginx:
    restart: always
    build:
      context: docker/local/nginx
      dockerfile: Dockerfile
    container_name: bookstore-nginx
    ports:
      - '8080:80'
    volumes:
      - media_volume:/app/mediafiles
    depends_on:
      - api
    networks:
      - flask_network

volumes:
  postgres_data:
  media_volume:

networks:
  flask_network:
