version: '3.9'
services:
  # api
  api:
    build:
      context: .
      dockerfile: ./docker/local/flask/Dockerfile
    container_name: bookstore-api
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - DOCKER_ENV=true
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:${POSTGRES_PORT}/${POSTGRES_DB}
      - API_HOST=${API_HOST}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    volumes:
      - .:/app
    networks:
      - bookstore_network
    depends_on:
      - postgres_db
      - mailhog

  # postgres
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bookstore_network

  # mailhog
  mailhog:
    image: jcalonso/mailhog:latest  # ARM64 compatible image
    container_name: bookstore-mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP server
    networks:
      - bookstore_network

  # nginx
  nginx:
    restart: always
    build:
      context: docker/local/nginx
      dockerfile: Dockerfile
    container_name: bookstore-nginx
    ports:
      - '8080:80'
    volumes:
      - media_volume:/app/mediafiles
    depends_on:
      - api
    networks:
      - bookstore_network

networks:
  bookstore_network:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
