"""Update order by adding billing information

Revision ID: 68489e6fc274
Revises: a053f5a0ac7a
Create Date: 2025-01-01 16:13:43.126603+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68489e6fc274'
down_revision: Union[str, None] = 'a053f5a0ac7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('billing_name', sa.String(length=100), nullable=True, server_default='Unknown'))
    op.add_column('orders', sa.Column('billing_email', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('billing_phone', sa.String(length=20), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('billing_street', sa.String(length=200), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('billing_city', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('billing_state', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('billing_postal_code', sa.String(length=20), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('billing_country', sa.String(length=100), nullable=True, server_default=''))
    
    op.add_column('orders', sa.Column('shipping_name', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_email', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(length=20), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_street', sa.String(length=200), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_state', sa.String(length=100), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True, server_default=''))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=True, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_street')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_email')
    op.drop_column('orders', 'shipping_name')
    op.drop_column('orders', 'billing_country')
    op.drop_column('orders', 'billing_postal_code')
    op.drop_column('orders', 'billing_state')
    op.drop_column('orders', 'billing_city')
    op.drop_column('orders', 'billing_street')
    op.drop_column('orders', 'billing_phone')
    op.drop_column('orders', 'billing_email')
    op.drop_column('orders', 'billing_name')
    # ### end Alembic commands ###
