"""Add OrderStatusChangeLog table

Revision ID: 6e99e54c1247
Revises: 0862a0bdd11b
Create Date: 2025-01-02 08:39:47.379954+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e99e54c1247'
down_revision: Union[str, None] = '0862a0bdd11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_change_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_change_logs_admin_id'), 'order_status_change_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_order_status_change_logs_created_at'), 'order_status_change_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_status_change_logs_id'), 'order_status_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_change_logs_order_id'), 'order_status_change_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_change_logs_order_id'), table_name='order_status_change_logs')
    op.drop_index(op.f('ix_order_status_change_logs_id'), table_name='order_status_change_logs')
    op.drop_index(op.f('ix_order_status_change_logs_created_at'), table_name='order_status_change_logs')
    op.drop_index(op.f('ix_order_status_change_logs_admin_id'), table_name='order_status_change_logs')
    op.drop_table('order_status_change_logs')
    # ### end Alembic commands ###
